In [1]:
exec(open("init_notebook.py", "r").read())
%load_ext autoreload
%autoreload 2

current working dirC:\Users\Renee\UCSC\cmpm194\carla-jaywalker-experiments

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib qt

In [3]:
from analysis.EpisodeParser import EpisodeParser
from analysis.Histogram import Histogram
from analysis.ScatterPlot import ScatterPlot
from analysis.TrajectoryPlotter import TrajectoryPlotter

In [4]:
# path = "logs/2022-06-02-drunken-static-trajectories.csv"
# path = "logs/2022-06-03-drunken-survival-trajectories.csv"
path = "logs/2022-06-06-00-00-trajectories.csv"
df = pd.read_csv(path)
episodeParser = EpisodeParser(df)
episodeParser.df.tail()

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_state,w_x_diff,w_y_diff,w_d,distance
9953,38,197,87.680740,191.591827,7.501051,63.398041,185.867493,1.730262,CROSSING,-0.060394,-0.060394,0.085410,24.948297
9954,38,198,88.046188,191.591965,7.432278,63.329456,185.816086,1.758599,CROSSING,-0.051407,-0.051407,0.072700,25.382624
9955,38,199,88.459160,191.592117,7.345066,63.248226,185.759827,1.769234,CROSSING,-0.056259,-0.056259,0.079562,25.876762
9956,38,200,88.765762,191.592239,7.288198,63.186073,185.719437,1.763067,CROSSING,-0.040390,-0.040390,0.057120,26.245196
9957,38,201,89.172218,191.592392,7.260334,63.102776,185.668167,-1.736997,CROSSING,-0.051270,-0.051270,0.072506,26.734103

# TODO
1. distance covered by the pedestrian
2. path with speed as color
3. cartoon
4. position of the pedestrian when vehicle crosses (we need the conflict point)
5. heatmap of x/y coordinate against time
6. x/y vs distance to the vehicle
7. velocity vs time
7. velocity vs distance

In [5]:
epiDistance = episodeParser.getDistanceCoveredByEpisode(1, 'w_d')

In [6]:

Histogram.plotNormalizedMetrics(epiDistance, "Pedestrian Distance Walked")

In [7]:
# can change episode
ep1 = episodeParser.getEpisodeDF(2)
ep1['color'] = (ep1['w_speed'] > 0.0).map({True: 'g', False: 'r'})
# ep1[ep1.color == 'r'].tail()
ep1.describe()

C:\Users\Renee\AppData\Local\Temp/ipykernel_12620/4231351966.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ep1['color'] = (ep1['w_speed'] > 0.0).map({True: 'g', False: 'r'})

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_x_diff,w_y_diff,w_d,distance
count,170.0,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,170.000000,169.000000,169.000000,169.000000,170.000000
mean,2.0,85.500000,19.722867,191.560913,1.397804,62.947652,192.340607,0.888846,-0.059579,-0.059579,0.091454,43.352525
std,0.0,49.218899,5.852328,0.002908,2.472658,0.100732,3.299597,0.815344,0.064659,0.064659,0.084199,5.888392
min,2.0,1.000000,8.441534,191.554413,0.000000,62.823261,185.463745,-1.793294,-0.542206,-0.542206,0.000000,39.426705
25%,2.0,43.250000,15.534494,191.558754,0.000000,62.880653,189.813858,0.384261,-0.093414,-0.093414,0.045985,39.531081
50%,2.0,85.500000,23.408833,191.562744,0.000000,62.930098,192.809410,0.927221,-0.060715,-0.060715,0.087482,39.663058
75%,2.0,127.750000,23.408833,191.562744,1.574565,62.973972,195.631016,1.506290,-0.031479,-0.031479,0.132475,47.501928
max,2.0,170.000000,23.408833,191.562744,8.701395,63.268623,195.962555,3.116689,0.430038,0.430038,0.766795,54.721787

In [8]:
episodeParser.df.describe()

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_x_diff,w_y_diff,w_d,distance
count,9958.000000,9958.000000,9958.000000,9958.000000,9958.000000,9958.000000,9958.000000,9958.000000,9920.000000,9920.000000,9920.000000,9958.000000
mean,18.755172,93.234887,32.947747,191.567056,3.081950,63.487470,192.313829,0.947914,-0.038119,-0.038119,0.102260,32.910782
std,11.228037,54.142909,19.136104,0.008461,3.117683,0.947873,3.235257,0.774646,0.410348,0.410348,0.573777,14.724913
min,1.000000,1.000000,8.054592,191.553436,0.000000,61.650959,185.135635,-3.355669,-0.551270,-0.551270,0.000000,1.166538
25%,8.000000,47.000000,20.506100,191.561401,0.000000,62.984964,189.801346,0.486455,-0.077087,-0.077087,0.033896,22.148089
50%,18.000000,93.000000,24.517893,191.563614,2.128623,63.145119,192.762360,1.018905,-0.051788,-0.051788,0.073898,39.263286
75%,29.000000,139.000000,44.024699,191.571716,7.054689,63.757874,195.588402,1.457157,-0.023460,-0.023460,0.109989,43.275191
max,38.000000,201.000000,112.683105,191.603088,8.701395,68.721794,196.000000,3.659014,10.739548,10.739548,15.188014,55.129555

In [9]:
# sns.relplot(data=ep1, x='w_x', y='w_y')
for i in range(5, 10):
    ep1 = episodeParser.getEpisodeDF(i)
    # ep1 = ep1.iloc[0:80]
    # sns.scatterplot(data=ep1, x='distance', y='w_y')
    ScatterPlot.plot2MetricsDF(ep1, 'w_x', 'w_y', 'x', 'y')

In [10]:
Histogram.plotNormalizedMetricsDF(episodeParser.df, 'w_speed', "Pedestrian Speed")

In [77]:
# sns.relplot(data=ep1, x='timestep', y='w_x', hue="color")

In [11]:
for i in range(5, 10):
    ep1 = episodeParser.getEpisodeDF(i)
    # ep1 = ep1.iloc[0:80]
    # sns.scatterplot(data=ep1, x='distance', y='w_y')
    ScatterPlot.plot2MetricsDF(ep1, 'timestep', 'w_y', 'distance to vehicle', 'w_y')

In [12]:
ep1.iloc[0:70]

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_state,w_x_diff,w_y_diff,w_d,distance
2620,9,1,19.361471,191.561127,0.8918,62.998745,195.985641,0.319302,INITALIZING,NaN,NaN,NaN,43.861008
2621,9,2,19.361471,191.561127,1.1662,62.998173,195.978958,0.198809,INITALIZING,-0.006683,-0.006683,0.009452,43.859765
2622,9,3,19.361471,191.561127,1.5778,62.997757,195.974045,0.000000,INITALIZING,-0.004913,-0.004913,0.006948,43.858856
2623,9,4,19.361471,191.561127,1.9894,62.997757,195.974045,0.000000,INITALIZING,0.000000,0.000000,0.000000,43.858856
2624,9,5,19.361471,191.561127,2.3324,62.997757,195.974045,0.000000,INITALIZING,0.000000,0.000000,0.000000,43.858856
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2685,9,66,19.361469,191.560974,0.0000,62.651348,194.893417,1.058968,CROSSING,-0.052414,-0.052414,0.074125,43.417955
2686,9,67,19.361469,191.560974,0.0000,62.626995,194.847870,1.053062,CROSSING,-0.045547,-0.045547,0.064414,43.390199
2687,9,68,19.361469,191.560974,0.0000,62.600311,194.795441,1.048175,CROSSING,-0.052429,-0.052429,0.074146,43.359650
2688,9,69,19.361469,191.560974,0.0000,62.578285,194.748962,1.049115,CROSSING,-0.046478,-0.046478,0.065730,43.334241
2689,9,70,19.361469,191.560974,0.0000,62.554901,194.694794,1.055721,CROSSING,-0.054169,-0.054169,0.076606,43.306967

In [13]:
ep1.describe()

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_x_diff,w_y_diff,w_d,distance
count,373.0,373.000000,373.000000,373.000000,373.000000,373.000000,373.000000,373.000000,372.000000,372.000000,372.000000,373.000000
mean,9.0,94.313673,21.477826,191.562034,1.166194,63.201355,192.446303,1.029501,-0.026327,-0.026327,0.113728,41.848673
std,0.0,54.875477,4.985562,0.002348,2.028946,0.624073,3.148128,0.621273,0.526557,0.526557,0.736849,5.036631
min,9.0,1.000000,11.374399,191.557266,0.000000,62.218842,185.905960,-0.027204,-0.546188,-0.546188,0.000000,30.097710
25%,9.0,47.000000,19.361469,191.560974,0.000000,62.904789,189.986435,0.639928,-0.068096,-0.068096,0.042268,35.506473
50%,9.0,94.000000,19.361469,191.560974,0.000000,63.013683,192.797150,1.098477,-0.056488,-0.056488,0.080005,43.503962
75%,9.0,140.000000,27.841537,191.564972,1.798080,63.322025,195.587982,1.402308,-0.029236,-0.029236,0.097149,44.978422
max,9.0,201.000000,33.426083,191.567886,7.554532,64.632439,195.985641,3.347482,10.060760,10.060760,14.228064,51.774812

In [14]:
ep1 = episodeParser.getEpisodeDF(8)
# sns.scatterplot(data=ep1, x='distance', y='w_y')
ScatterPlot.plot2MetricsDF(ep1, 'timestep', 'w_speed', 'timestep', 'speed')

In [15]:

TrajectoryPlotter.plot2MetricsDF(df, 'timestep', 'w_y', 'timestep', 'w_y')