In [1]:
exec(open("init_notebook.py", "r").read())
%load_ext autoreload
%autoreload 2

current working dirC:\Users\ryanc\Documents\GitHub\CM194\carla-jaywalker-experiments

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib qt

In [3]:
from analysis.EpisodeParser import EpisodeParser
from analysis.Histogram import Histogram
from analysis.ScatterPlot import ScatterPlot
from analysis.TrajectoryPlotter import TrajectoryPlotter

In [4]:
#path = "logs/2022-06-02-drunken-static-trajectories.csv"
# path = "logs/2022-06-03-drunken-survival-trajectories.csv"
path = "logs/2022-06-03-00-00-trajectories.csv"
df = pd.read_csv(path)
episodeParser = EpisodeParser(df)
episodeParser.df.tail()

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_state,w_x_diff,w_y_diff,w_d,distance
3842,39,122,21.589678,191.562653,0.0,62.495518,186.521317,1.997986,CROSSING,-0.120987,-0.120987,0.171101,41.215323
3843,39,123,21.589678,191.562653,0.0,62.612286,186.400360,2.002344,CROSSING,-0.120956,-0.120956,0.171058,41.346144
3844,39,124,21.589678,191.562653,0.0,62.728935,186.279617,1.997914,CROSSING,-0.120743,-0.120743,0.170756,41.477090
3845,39,125,21.589678,191.562653,0.0,62.855522,186.148651,2.002344,CROSSING,-0.130966,-0.130966,0.185214,41.619482
3846,39,126,21.589678,191.562653,0.0,62.972080,186.027908,1.996945,CROSSING,-0.120743,-0.120743,0.170756,41.750888

# TODO
1. distance covered by the pedestrian
2. path with speed as color
3. cartoon
4. position of the pedestrian when vehicle crosses (we need the conflict point)
5. heatmap of x/y coordinate against time
6. x/y vs distance to the vehicle
7. velocity vs time
7. velocity vs distance

In [26]:
epiDistance = episodeParser.getDistanceCoveredByEpisode(1, 'w_d')

In [31]:

Histogram.plotNormalizedMetrics(epiDistance, "Pedestrian Distance Walked")

In [32]:
ep1 = episodeParser.getEpisodeDF(2)
ep1['color'] = (ep1['w_speed'] > 0.0).map({True: 'g', False: 'r'})
# ep1[ep1.color == 'r'].tail()
ep1.describe()

c:\Users\ryanc\anaconda3\envs\carlaEnv\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_x_diff,w_y_diff,w_d,distance
count,81.0,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,80.000000,80.000000,80.000000,81.000000
mean,2.0,41.000000,34.037860,191.567531,6.016851,61.384486,194.779462,0.930202,-0.045058,-0.045058,0.063722,27.540226
std,0.0,23.526581,12.186142,0.005266,2.120349,1.608873,1.271966,0.804921,0.064068,0.064068,0.090606,13.813127
min,2.0,1.000000,19.053308,191.560928,0.686000,58.515903,192.333145,-0.020229,-0.539902,-0.539902,0.000000,2.533220
25%,2.0,21.000000,21.900476,191.562469,4.859089,59.778652,193.861923,0.045077,-0.067955,-0.067955,0.003032,15.331744
50%,2.0,41.000000,32.773220,191.566971,7.205380,62.062153,195.383026,0.923659,-0.040512,-0.040512,0.057293,29.536484
75%,2.0,61.000000,44.546440,191.572006,7.455954,62.893787,195.893417,1.506645,-0.002144,-0.002144,0.096103,41.221459
max,2.0,81.000000,56.098183,191.576950,7.803557,62.938274,195.937790,3.558058,0.000000,0.000000,0.763536,44.102684

In [19]:
episodeParser.df.describe()

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_x_diff,w_y_diff,w_d,distance
count,3847.000000,3847.000000,3847.000000,3847.000000,3847.000000,3847.000000,3847.000000,3847.000000,3808.000000,3808.000000,3808.000000,3847.000000
mean,20.053288,52.168703,26.922374,191.564066,2.943947,61.527665,193.599081,0.945100,-0.065769,-0.065769,0.093011,34.765949
std,11.440571,32.326771,10.937712,0.005418,3.051047,1.691139,2.689120,0.974709,0.069766,0.069766,0.098665,12.125196
min,1.000000,1.000000,9.180870,191.550934,0.000000,53.272846,185.978165,-4.116518,-0.639374,-0.639374,0.000000,2.327496
25%,10.000000,25.000000,20.004253,191.560974,0.000000,60.311777,192.264946,0.003139,-0.097931,-0.097931,0.012753,31.296851
50%,20.000000,50.000000,22.810234,191.563049,1.948107,62.342609,194.718079,1.088420,-0.059570,-0.059570,0.084245,38.369569
75%,30.000000,75.000000,30.863580,191.566429,6.581156,62.903681,195.866028,1.721962,-0.009018,-0.009018,0.138495,42.931446
max,39.000000,138.000000,58.375095,191.578400,8.764176,63.066242,196.000000,3.995766,0.000000,0.000000,0.904211,54.022276

In [43]:
sns.relplot(data=ep1, x='w_x', y='w_y')
for i in range(5, 10):
    ep1 = episodeParser.getEpisodeDF(i)
    # ep1 = ep1.iloc[0:80]
    # sns.scatterplot(data=ep1, x='distance', y='w_y')
    ScatterPlot.plot2MetricsDF(ep1, 'w_x', 'w_y', 'x', 'y')

In [34]:
Histogram.plotNormalizedMetricsDF(episodeParser.df, 'w_speed', "Pedestrian Speed")

In [25]:
#sns.relplot(data=ep1, x='timestep', y='w_x', hue="w_x")

In [35]:
for i in range(5, 10):
    ep1 = episodeParser.getEpisodeDF(i)
    # ep1 = ep1.iloc[0:80]
    # sns.scatterplot(data=ep1, x='distance', y='w_y')
    ScatterPlot.plot2MetricsDF(ep1, 'timestep', 'w_y', 'distance to vehicle', 'w_y')

In [38]:
ep1.iloc[0:70]

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_state,w_x_diff,w_y_diff,w_d,distance
740,8,1,17.934732,191.560471,0.823200,62.927483,195.928421,1.213861,INITALIZING,NaN,NaN,NaN,45.204276
741,8,2,17.934732,191.560471,1.372000,62.898384,195.899216,0.467594,INITALIZING,-0.029205,-0.029205,0.041303,45.172499
742,8,3,17.934732,191.560471,1.920800,62.887192,195.887894,0.180528,INITALIZING,-0.011322,-0.011322,0.016012,45.160272
743,8,4,17.934732,191.560471,2.469600,62.884541,195.885208,0.000000,INITALIZING,-0.002686,-0.002686,0.003798,45.157376
744,8,5,17.934732,191.560471,3.018399,62.884541,195.885208,0.000000,INITALIZING,0.000000,0.000000,0.000000,45.157376
...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,8,66,18.921215,191.550934,0.000000,62.456059,191.711136,1.266236,CROSSING,-0.096939,-0.096939,0.137093,43.535138
806,8,67,18.921215,191.550934,0.000000,62.461582,191.621185,1.294341,CROSSING,-0.089951,-0.089951,0.127209,43.540424
807,8,68,18.921215,191.550934,0.000000,62.467396,191.529297,1.322451,CROSSING,-0.091888,-0.091888,0.129950,43.546186
808,8,69,18.921215,191.550934,0.000000,62.474125,191.426010,1.350565,CROSSING,-0.103287,-0.103287,0.146070,43.553089
809,8,70,18.921215,191.550934,0.000000,62.480526,191.330215,1.378683,CROSSING,-0.095795,-0.095795,0.135474,43.559870

In [39]:
ep1.describe()

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_x_diff,w_y_diff,w_d,distance
count,109.0,109.000000,109.000000,109.000000,109.000000,109.000000,109.000000,109.000000,108.000000,108.000000,108.000000,109.000000
mean,8.0,55.000000,18.777930,191.552683,0.282465,62.677479,192.522710,1.250193,-0.090818,-0.090818,0.128436,44.025460
std,0.0,31.609598,0.327089,0.003709,0.704953,0.189472,3.209283,0.851154,0.077425,0.077425,0.109496,0.517639
min,8.0,1.000000,17.934732,191.550934,0.000000,62.399975,186.120117,-0.019531,-0.623703,-0.623703,0.000000,43.508117
25%,8.0,28.000000,18.921215,191.550934,0.000000,62.485252,189.952698,0.416789,-0.139023,-0.139023,0.025312,43.595032
50%,8.0,55.000000,18.921215,191.550934,0.000000,62.676926,192.657150,1.406805,-0.099998,-0.099998,0.141419,43.883536
75%,8.0,82.000000,18.921215,191.550934,0.000000,62.884270,195.856339,1.991975,-0.017899,-0.017899,0.196608,44.176492
max,8.0,109.000000,18.921215,191.561417,3.635798,62.987465,195.928421,3.904932,0.000000,0.000000,0.882049,45.204276

In [40]:
ep1 = episodeParser.getEpisodeDF(8)
# sns.scatterplot(data=ep1, x='distance', y='w_y')
ScatterPlot.plot2MetricsDF(ep1, 'timestep', 'w_speed', 'timestep', 'speed')

In [42]:

TrajectoryPlotter.plot2MetricsDF(df, 'timestep', 'w_y', 'timestep', 'w_y')