In [1]:
exec(open("init_notebook.py", "r").read())
%load_ext autoreload
%autoreload 2

current working dirC:\AV\Carla\CARLA_0.9.13\WindowsNoEditor\PythonAPI\experiments

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib qt

In [3]:
from analysis.EpisodeParser import EpisodeParser
from analysis.Histogram import Histogram
from analysis.ScatterPlot import ScatterPlot
from analysis.TrajectoryPlotter import TrajectoryPlotter

In [4]:
path = "logs/2022-06-02-drunken-static-trajectories.csv"
# path = "logs/2022-06-03-drunken-survival-trajectories.csv"
path = "logs/2022-12-23-00-00-trajectories.csv"
df = pd.read_csv(path)
# df.tail()
episodeParser = EpisodeParser(df)
episodeParser.df.tail()

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_state,w_x_diff,w_y_diff,w_d,distance
397,1,197,-133.556625,-42.804146,7.416306,-112.691322,-16.905727,-29.368923,CROSSING,-0.048031,-0.048031,0.067926,33.257916
398,1,198,-134.056763,-42.636497,7.636960,-112.671112,-16.949223,-30.054701,CROSSING,-0.043495,-0.043495,0.061511,33.424275
399,1,199,-134.614975,-42.447186,7.621245,-112.648872,-16.996872,-30.809067,CROSSING,-0.047649,-0.047649,0.067386,33.618866
400,1,200,-135.111771,-42.274750,7.413463,-112.628662,-17.039999,-31.494860,CROSSING,-0.043127,-0.043127,0.060991,33.797675
401,1,201,-135.594238,-42.109028,7.206396,-112.608444,-17.082941,-32.180660,CROSSING,-0.042942,-0.042942,0.060729,33.980167

# TODO
1. distance covered by the pedestrian
2. path with speed as color
3. cartoon
4. position of the pedestrian when vehicle crosses (we need the conflict point)
5. heatmap of x/y coordinate against time
6. x/y vs distance to the vehicle
7. velocity vs time
7. velocity vs distance

In [5]:
epiDistance = episodeParser.getDistanceCoveredByEpisode(1, 'w_d')

In [6]:

Histogram.plotNormalizedMetrics(epiDistance, "Pedestrian Distance Walked")

In [32]:
ep1 = episodeParser.getEpisodeDF(1)
ep1['color'] = (ep1['w_speed'] > 0.0).map({True: 'g', False: 'r'})
# ep1[ep1.color == 'r'].tail()
ep1.describe()

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_x_diff,w_y_diff,w_d,distance
count,402.0,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,401.000000,401.000000,401.000000,402.000000
mean,1.0,101.000000,-118.144038,-20.436367,6.571650,-113.352245,-9.120704,-1.361086,-0.035120,-0.035120,0.119084,20.381686
std,0.0,58.095287,15.338031,14.853225,1.691023,0.837752,4.371890,6.287631,0.247858,0.247858,0.333352,10.612449
min,1.0,1.000000,-151.068954,-44.110245,0.096326,-115.104561,-17.082941,-32.180660,-0.503323,-0.503323,0.000000,1.084300
25%,1.0,51.000000,-130.399185,-36.544169,6.740417,-113.759069,-12.212310,-0.941502,-0.114280,-0.114280,0.045752,11.394231
50%,1.0,101.000000,-115.343571,-12.573427,7.236481,-113.349812,-9.632795,0.340792,-0.047955,-0.047955,0.086469,21.756495
75%,1.0,151.000000,-104.154974,-6.909639,7.439059,-113.033310,-4.803897,1.386048,0.000000,0.000000,0.168983,28.905040
max,1.0,201.000000,-99.542465,-6.728538,8.631611,-111.199013,-2.888735,2.381529,4.643490,4.643490,6.566886,38.361667

In [33]:
ep1.head()

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_state,w_x_diff,w_y_diff,w_d,distance,color
0,1,1,-151.068954,-7.729922,1.097600,-113.0,-3.0,0.0,INITALIZING,NaN,NaN,NaN,38.361667,r
1,1,2,-151.068954,-7.729922,1.715000,-113.0,-3.0,0.0,INITALIZING,0.0,0.0,0.0,38.361667,r
2,1,3,-151.068954,-7.729922,2.332400,-113.0,-3.0,0.0,INITALIZING,0.0,0.0,0.0,38.361667,r
3,1,4,-151.068954,-7.729922,2.881199,-113.0,-3.0,0.0,INITALIZING,0.0,0.0,0.0,38.361667,r
4,1,5,-151.068954,-7.729922,3.498598,-113.0,-3.0,0.0,INITALIZING,0.0,0.0,0.0,38.361667,r

In [35]:
ep1[ep1["w_speed"] < -10].head()

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_state,w_x_diff,w_y_diff,w_d,distance,color
371,1,171,-119.607559,-43.904366,7.386349,-113.239441,-15.675367,-10.519290,CROSSING,-0.049726,-0.049726,0.070324,28.938370,r
372,1,172,-120.165840,-43.952076,7.209886,-113.218063,-15.725073,-11.272314,CROSSING,-0.049706,-0.049706,0.070294,29.069491,r
373,1,173,-120.714195,-44.001026,7.127352,-113.196602,-15.774763,-12.025537,CROSSING,-0.049690,-0.049690,0.070273,29.210206,r
374,1,174,-121.213142,-44.038090,7.177193,-113.177071,-15.819921,-12.710426,CROSSING,-0.045157,-0.045157,0.063862,29.340135,r
375,1,175,-121.719604,-44.054153,7.312422,-113.157516,-15.865060,-13.395429,CROSSING,-0.045139,-0.045139,0.063837,29.460726,r

In [26]:
episodeParser.df.describe()

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_x_diff,w_y_diff,w_d,distance
count,402.0,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,401.000000,401.000000,401.000000,402.000000
mean,1.0,101.000000,-118.144038,-20.436367,6.571650,-113.352245,-9.120704,-1.361086,-0.035120,-0.035120,0.119084,20.381686
std,0.0,58.095287,15.338031,14.853225,1.691023,0.837752,4.371890,6.287631,0.247858,0.247858,0.333352,10.612449
min,1.0,1.000000,-151.068954,-44.110245,0.096326,-115.104561,-17.082941,-32.180660,-0.503323,-0.503323,0.000000,1.084300
25%,1.0,51.000000,-130.399185,-36.544169,6.740417,-113.759069,-12.212310,-0.941502,-0.114280,-0.114280,0.045752,11.394231
50%,1.0,101.000000,-115.343571,-12.573427,7.236481,-113.349812,-9.632795,0.340792,-0.047955,-0.047955,0.086469,21.756495
75%,1.0,151.000000,-104.154974,-6.909639,7.439059,-113.033310,-4.803897,1.386048,0.000000,0.000000,0.168983,28.905040
max,1.0,201.000000,-99.542465,-6.728538,8.631611,-111.199013,-2.888735,2.381529,4.643490,4.643490,6.566886,38.361667

In [22]:
# sns.relplot(data=ep1, x='w_x', y='w_y')
for i in range(0, 1):
    ep1 = episodeParser.getEpisodeDF(i)
    # ep1 = ep1.iloc[0:80]
    # sns.scatterplot(data=ep1, x='distance', y='w_y')
    ScatterPlot.plot2MetricsDF(ep1, 'w_x', 'w_y', 'x', 'y')

In [23]:
Histogram.plotNormalizedMetricsDF(episodeParser.df, 'w_speed', "Pedestrian Speed")

In [17]:
# sns.relplot(data=ep1, x='timestep', y='w_x', hue="color")

In [18]:
for i in range(5, 10):
    ep1 = episodeParser.getEpisodeDF(i)
    # ep1 = ep1.iloc[0:80]
    # sns.scatterplot(data=ep1, x='distance', y='w_y')
    ScatterPlot.plot2MetricsDF(ep1, 'timestep', 'w_y', 'distance to vehicle', 'w_y')

In [19]:
ep1.iloc[0:70]

Empty DataFrame
Columns: [episode, timestep, v_x, v_y, v_speed, w_x, w_y, w_speed, w_state, w_x_diff, w_y_diff, w_d, distance]
Index: []

In [69]:
ep1.describe()

,episode,timestep,v_x,v_y,v_speed,w_x,w_y,w_speed,w_x_diff,w_y_diff,w_d,distance
count,314.0,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,314.000000,313.000000,313.000000,313.000000,314.000000
mean,5.0,85.165605,39.743183,191.568250,2.542089,64.514306,194.562312,0.507745,-0.031988,-0.031988,0.053070,36.827947
std,0.0,54.713059,32.659242,0.014355,3.344294,3.447107,2.682894,0.873141,0.078456,0.078456,0.107416,14.130152
min,5.0,1.000000,17.022257,191.535172,0.000000,62.933132,185.963333,-2.003093,-0.711502,-0.711502,0.000000,1.171180
25%,5.0,40.000000,20.278332,191.561462,0.000000,62.979961,194.726490,0.000000,-0.002991,-0.002991,0.000000,34.861146
50%,5.0,79.000000,20.278332,191.561462,0.000000,62.979961,195.975616,0.000000,0.000000,0.000000,0.000000,42.929173
75%,5.0,122.750000,51.562526,191.569637,7.079969,63.000000,195.975616,1.250000,0.000000,0.000000,0.057746,42.929173
max,5.0,201.000000,132.112335,191.612457,7.965191,76.656372,196.000000,3.041976,0.262146,0.262146,1.006216,69.409472

In [83]:
ep1 = episodeParser.getEpisodeDF(8)
# sns.scatterplot(data=ep1, x='distance', y='w_y')
ScatterPlot.plot2MetricsDF(ep1, 'timestep', 'w_speed', 'timestep', 'speed')

In [17]:

TrajectoryPlotter.plot2MetricsDF(df, 'timestep', 'w_y', 'timestep', 'w_y')